import { useEffect, useState, type FormEvent } from "react";
import { PageContainer, PageHeader } from "@/components/page";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useAppShell } from "@/hooks/use-app-shell";
import { washApi, type Customer, type Vehicle, type VehicleType } from "@/lib/controlwash";
import { useI18n } from "@/lib/i18n";

export function CustomersVehiclesPage() {
	const { t } = useI18n(); const shell = useAppShell(); const [customers, setCustomers] = useState<Customer[]>([]); const [vehicles, setVehicles] = useState<Vehicle[]>([]); const [types, setTypes] = useState<VehicleType[]>([]); const [mode, setMode] = useState<"customer" | "vehicle" | null>(null); const [query, setQuery] = useState(""); const [failed, setFailed] = useState(false);
	async function load(search = query) { setFailed(false); try { const [customerData, vehicleData, typeData] = await Promise.all([washApi.customers(shell.organizationId, search), washApi.vehicles(shell.organizationId, search), washApi.vehicleTypes(shell.organizationId)]); setCustomers(customerData.customers); setVehicles(vehicleData.vehicles); setTypes(typeData.vehicleTypes.filter((item) => item.isActive)); } catch { setFailed(true); } }
	useEffect(() => { let active = true; Promise.all([washApi.customers(shell.organizationId), washApi.vehicles(shell.organizationId), washApi.vehicleTypes(shell.organizationId)]).then(([customerData, vehicleData, typeData]) => { if (active) { setCustomers(customerData.customers); setVehicles(vehicleData.vehicles); setTypes(typeData.vehicleTypes.filter((item) => item.isActive)); } }).catch(() => { if (active) setFailed(true); }); return () => { active = false; }; }, [shell.organizationId]);
	return <PageContainer className="space-y-6"><PageHeader title={t("Customers and vehicles")} description={t("Save frequent visitors, but keep walk-in washes fast and optional.")} actions={<div className="flex gap-2"><Button variant="outline" onClick={() => setMode("customer")}>{t("New customer")}</Button><Button onClick={() => setMode("vehicle")}>{t("New vehicle")}</Button></div>} /><form className="flex gap-2" onSubmit={(event) => { event.preventDefault(); void load(); }}><Input value={query} placeholder={t("Search by name, phone or plate")} onChange={(event) => setQuery(event.target.value)} /><Button variant="outline">{t("Search")}</Button></form>{failed ? <p role="alert">{t("We could not load customers and vehicles.")}</p> : null}{mode ? <DirectoryForm mode={mode} customers={customers} types={types} onCancel={() => setMode(null)} onSaved={async () => { setMode(null); await load(""); }} /> : null}<div className="grid gap-5 lg:grid-cols-2"><section><h2 className="mb-3 text-lg font-semibold">{t("Customers")}</h2><div className="rounded-2xl border">{customers.map((customer) => <div key={customer.id} className="border-b p-4 last:border-b-0"><p className="font-medium">{customer.displayName}</p><p className="text-sm text-muted-foreground">{[customer.phone, customer.email].filter(Boolean).join(" · ") || t("No contact details")}</p></div>)}{!customers.length ? <p className="p-6 text-center text-muted-foreground">{t("No customers found.")}</p> : null}</div></section><section><h2 className="mb-3 text-lg font-semibold">{t("Vehicles")}</h2><div className="rounded-2xl border">{vehicles.map((vehicle) => <div key={vehicle.id} className="border-b p-4 last:border-b-0"><p className="font-medium">{vehicle.plate || `${vehicle.make ?? ""} ${vehicle.model ?? ""}`.trim() || vehicle.vehicleTypeName}</p><p className="text-sm text-muted-foreground">{vehicle.vehicleTypeName}{vehicle.customerName ? ` · ${vehicle.customerName}` : ""}</p></div>)}{!vehicles.length ? <p className="p-6 text-center text-muted-foreground">{t("No vehicles found.")}</p> : null}</div></section></div></PageContainer>;
}

function DirectoryForm({ mode, customers, types, onCancel, onSaved }: { mode: "customer" | "vehicle"; customers: Customer[]; types: VehicleType[]; onCancel: () => void; onSaved: () => Promise<void> }) {
	const { t } = useI18n(); const shell = useAppShell(); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [email, setEmail] = useState(""); const [customerId, setCustomerId] = useState(""); const [typeId, setTypeId] = useState(types[0]?.id ?? ""); const [plate, setPlate] = useState(""); const [make, setMake] = useState(""); const [model, setModel] = useState(""); const [pending, setPending] = useState(false); const [failed, setFailed] = useState(false);
	async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setFailed(false); try { if (mode === "customer") await washApi.createCustomer(shell.organizationId, { displayName: name, phone: phone || null, email: email || null }); else await washApi.createVehicle(shell.organizationId, { customerId: customerId || null, vehicleTypeId: typeId, plate: plate || null, make: make || null, model: model || null }); await onSaved(); } catch { setFailed(true); } finally { setPending(false); } }
	return <form onSubmit={submit} className="rounded-2xl border p-5"><div className="mb-4 flex justify-between"><h2 className="font-semibold">{t(mode === "customer" ? "New customer" : "New vehicle")}</h2><Button type="button" variant="ghost" onClick={onCancel}>{t("Cancel")}</Button></div><div className="grid gap-4 sm:grid-cols-2">{mode === "customer" ? <><div className="grid gap-2"><Label>{t("Name")}</Label><Input value={name} required onChange={(event) => setName(event.target.value)} /></div><div className="grid gap-2"><Label>{t("Phone")}</Label><Input value={phone} onChange={(event) => setPhone(event.target.value)} /></div><div className="grid gap-2"><Label>{t("Email")}</Label><Input type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></div></> : <><div className="grid gap-2"><Label>{t("Vehicle type")}</Label><select className="h-10 rounded-md border bg-background px-3" value={typeId} onChange={(event) => setTypeId(event.target.value)}>{types.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</select></div><div className="grid gap-2"><Label>{t("Customer")}</Label><select className="h-10 rounded-md border bg-background px-3" value={customerId} onChange={(event) => setCustomerId(event.target.value)}><option value="">{t("No customer")}</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.displayName}</option>)}</select></div><div className="grid gap-2"><Label>{t("Plate")}</Label><Input value={plate} onChange={(event) => setPlate(event.target.value)} /></div><div className="grid gap-2"><Label>{t("Make")}</Label><Input value={make} onChange={(event) => setMake(event.target.value)} /></div><div className="grid gap-2"><Label>{t("Model")}</Label><Input value={model} onChange={(event) => setModel(event.target.value)} /></div></>}</div>{failed ? <p role="alert" className="mt-3 text-sm text-destructive">{t("We could not save this record.")}</p> : null}<Button className="mt-4" disabled={pending}>{t(pending ? "Saving…" : "Save")}</Button></form>;
}
