import { useEffect, useState, type FormEvent } from "react";
import { ArrowLeftRight, CircleDollarSign, MinusCircle, PlusCircle } from "lucide-react";
import { PageContainer, PageHeader } from "@/components/page";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useAppShell } from "@/hooks/use-app-shell";
import { amountFromInput, formatMoney, washApi, type FinancialMovement, type PaymentMethod } from "@/lib/controlwash";
import { useI18n } from "@/lib/i18n";

export function FinancePage() {
	const { t, locale } = useI18n(); const shell = useAppShell(); const [methods, setMethods] = useState<PaymentMethod[]>([]); const [movements, setMovements] = useState<FinancialMovement[]>([]); const [categories, setCategories] = useState<{ id: string; name: string }[]>([]); const [currency, setCurrency] = useState("COP"); const [mode, setMode] = useState<"expense" | "adjustment" | "transfer" | null>(null); const [failed, setFailed] = useState(false);
	async function load() { setFailed(false); try { const [balances, ledger, catalog] = await Promise.all([washApi.balances(shell.organizationId), washApi.movements(shell.organizationId), washApi.expenseCategories(shell.organizationId)]); setMethods(balances.balances.filter((item) => item.isActive)); setMovements(ledger.movements); setCategories(catalog.categories.filter((item) => item.isActive)); setCurrency(balances.currency); } catch { setFailed(true); } }
	useEffect(() => { let active = true; Promise.all([washApi.balances(shell.organizationId), washApi.movements(shell.organizationId), washApi.expenseCategories(shell.organizationId)]).then(([balances, ledger, catalog]) => { if (active) { setMethods(balances.balances.filter((item) => item.isActive)); setMovements(ledger.movements); setCategories(catalog.categories.filter((item) => item.isActive)); setCurrency(balances.currency); } }).catch(() => { if (active) setFailed(true); }); return () => { active = false; }; }, [shell.organizationId]);
	return <PageContainer className="space-y-6"><PageHeader title={t("Cash and movements")} description={t("See recorded balances and register every inflow, expense or correction.")} actions={<div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => setMode("expense")}><MinusCircle className="size-4" />{t("Expense")}</Button><Button size="sm" variant="outline" onClick={() => setMode("adjustment")}><PlusCircle className="size-4" />{t("Adjustment")}</Button><Button size="sm" onClick={() => setMode("transfer")}><ArrowLeftRight className="size-4" />{t("Move balance")}</Button></div>} />
		{failed ? <p role="alert">{t("We could not load cash movements.")}</p> : null}<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{methods.map((method) => <div key={method.id} className="rounded-2xl border p-4"><div className="mb-3 flex items-center gap-2 text-muted-foreground"><CircleDollarSign className="size-4" /><span className="text-sm">{method.systemKey === "cash" ? t("Cash") : method.name}</span></div><strong className="text-2xl">{formatMoney(method.balanceMinor ?? 0, currency, locale)}</strong><p className="mt-1 text-xs text-muted-foreground">{t("Recorded balance")}</p></div>)}</div>
		{mode ? <FinanceForm mode={mode} methods={methods} categories={categories} onCancel={() => setMode(null)} onSaved={async () => { setMode(null); await load(); }} /> : null}
		<section><h2 className="mb-3 text-lg font-semibold">{t("Recent movements")}</h2><div className="overflow-hidden rounded-2xl border">{movements.slice(0, 50).map((movement) => <div key={movement.id} className="flex items-center justify-between gap-4 border-b p-4 last:border-b-0"><div><p className="font-medium">{movement.description}</p><p className="text-sm text-muted-foreground">{movement.paymentMethodName} · {new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" }).format(new Date(movement.createdAt))}</p></div><strong className={movement.amountMinor >= 0 ? "text-emerald-700" : "text-foreground"}>{movement.amountMinor >= 0 ? "+" : ""}{formatMoney(movement.amountMinor, currency, locale)}</strong></div>)}{!movements.length ? <p className="p-8 text-center text-muted-foreground">{t("No movements yet.")}</p> : null}</div></section>
	</PageContainer>;
}

function FinanceForm({ mode, methods, categories, onCancel, onSaved }: { mode: "expense" | "adjustment" | "transfer"; methods: PaymentMethod[]; categories: { id: string; name: string }[]; onCancel: () => void; onSaved: () => Promise<void> }) {
	const { t } = useI18n(); const shell = useAppShell(); const [method, setMethod] = useState(methods[0]?.id ?? ""); const [toMethod, setToMethod] = useState(methods[1]?.id ?? ""); const [category, setCategory] = useState(categories[0]?.id ?? ""); const [amount, setAmount] = useState(""); const [description, setDescription] = useState(""); const [pending, setPending] = useState(false); const [failed, setFailed] = useState(false);
	async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setFailed(false); try { const amountMinor = amountFromInput(amount); if (mode === "expense") await washApi.createExpense(shell.organizationId, { categoryId: category, paymentMethodId: method, amountMinor, description }); else if (mode === "adjustment") await washApi.createAdjustment(shell.organizationId, { paymentMethodId: method, amountMinor, description, reason: description }); else await washApi.createTransfer(shell.organizationId, { fromPaymentMethodId: method, toPaymentMethodId: toMethod, amountMinor, reason: description }); await onSaved(); } catch { setFailed(true); } finally { setPending(false); } }
	return <form onSubmit={submit} className="rounded-2xl border p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold">{t(mode === "expense" ? "Record expense" : mode === "adjustment" ? "Adjust balance" : "Move balance between methods")}</h2><Button type="button" variant="ghost" onClick={onCancel}>{t("Cancel")}</Button></div><div className="grid gap-4 sm:grid-cols-2">{mode === "expense" ? <div className="grid gap-2"><Label>{t("Category")}</Label><select className="h-10 rounded-md border bg-background px-3" value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div> : null}<div className="grid gap-2"><Label>{t(mode === "transfer" ? "From" : "Payment method")}</Label><select className="h-10 rounded-md border bg-background px-3" value={method} onChange={(event) => setMethod(event.target.value)}>{methods.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>{mode === "transfer" ? <div className="grid gap-2"><Label>{t("To")}</Label><select className="h-10 rounded-md border bg-background px-3" value={toMethod} onChange={(event) => setToMethod(event.target.value)}>{methods.filter((item) => item.id !== method).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div> : null}<div className="grid gap-2"><Label>{t("Amount")}</Label><Input inputMode="numeric" value={amount} placeholder="50000" required onChange={(event) => setAmount(event.target.value)} /></div><div className="grid gap-2 sm:col-span-2"><Label>{t(mode === "expense" ? "Description" : "Reason")}</Label><Input value={description} maxLength={200} required onChange={(event) => setDescription(event.target.value)} /></div></div>{failed ? <p role="alert" className="mt-3 text-sm text-destructive">{t("We could not save the movement.")}</p> : null}<Button className="mt-4" disabled={pending || !amountFromInput(amount) || (mode === "transfer" && method === toMethod)}>{t(pending ? "Saving…" : "Save movement")}</Button></form>;
}
