import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Plus, RefreshCw, Timer, WalletCards } from "lucide-react";
import { PageContainer, PageHeader } from "@/components/page";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useAppShell } from "@/hooks/use-app-shell";
import { useI18n } from "@/lib/i18n";
import { formatMoney, washApi, type PaymentMethod, type Service, type Ticket, type VehicleType, type Worker } from "@/lib/controlwash";

type Data = { tickets: Ticket[]; services: Service[]; vehicleTypes: VehicleType[]; workers: Worker[]; methods: PaymentMethod[]; currency: string };
const columns = ["waiting", "in_progress", "ready"] as const;

export function QueuePage() {
	const { t, locale } = useI18n(); const shell = useAppShell(); const [data, setData] = useState<Data | null>(null); const [failed, setFailed] = useState(false); const [creating, setCreating] = useState(false); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
	async function load() { setFailed(false); try { const [tickets, services, vehicleTypes, workers, methods] = await Promise.all([washApi.tickets(shell.organizationId), washApi.services(shell.organizationId), washApi.vehicleTypes(shell.organizationId), washApi.workers(shell.organizationId), washApi.paymentMethods(shell.organizationId)]); setData({ tickets: tickets.tickets, currency: tickets.currency, services: services.services.filter((item) => item.isActive), vehicleTypes: vehicleTypes.vehicleTypes.filter((item) => item.isActive), workers: workers.workers.filter((item) => item.isActive), methods: methods.methods.filter((item) => item.isActive) }); } catch { setFailed(true); } }
	useEffect(() => { let active = true; Promise.all([washApi.tickets(shell.organizationId), washApi.services(shell.organizationId), washApi.vehicleTypes(shell.organizationId), washApi.workers(shell.organizationId), washApi.paymentMethods(shell.organizationId)]).then(([tickets, services, vehicleTypes, workers, methods]) => { if (active) setData({ tickets: tickets.tickets, currency: tickets.currency, services: services.services.filter((item) => item.isActive), vehicleTypes: vehicleTypes.vehicleTypes.filter((item) => item.isActive), workers: workers.workers.filter((item) => item.isActive), methods: methods.methods.filter((item) => item.isActive) }); }).catch(() => { if (active) setFailed(true); }); return () => { active = false; }; }, [shell.organizationId]);
	async function transition(ticket: Ticket, to: string) { setBusy(ticket.id); setError(null); try { await washApi.transitionTicket(shell.organizationId, ticket.id, { to, expectedVersion: ticket.version }); await load(); } catch (reason) { setError(reason instanceof Error && reason.message === "DELIVERY_PAYMENT_REQUIRED" ? t("Record payment before delivery.") : t("We could not update the wash.")); } finally { setBusy(null); } }
	async function collect(ticket: Ticket, methodId: string) { setBusy(ticket.id); setError(null); try { await washApi.recordPayment(shell.organizationId, ticket.id, { paymentMethodId: methodId, amountMinor: ticket.totalMinor }); await load(); } catch { setError(t("We could not record the payment.")); } finally { setBusy(null); } }
	return <PageContainer className="max-w-7xl space-y-6"><PageHeader title={t("Wash queue")} description={t("Receive a vehicle, follow its progress and collect payment without losing the queue.")} actions={<div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => void load()}><RefreshCw className="size-4" />{t("Refresh")}</Button><Button size="sm" onClick={() => setCreating((value) => !value)}><Plus className="size-4" />{t("New wash")}</Button></div>} />
		{error ? <p role="alert" className="rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm">{error}</p> : null}{failed ? <p role="alert">{t("We could not load the wash queue.")}</p> : null}
		{creating && data ? <NewWashForm data={data} onCancel={() => setCreating(false)} onCreated={async () => { setCreating(false); await load(); }} /> : null}
		{!data && !failed ? <p role="status">{t("Loading washes…")}</p> : null}{data ? <div className="grid gap-4 lg:grid-cols-3">{columns.map((status) => <section key={status} className="rounded-2xl bg-muted/50 p-3"><header className="mb-3 flex items-center justify-between"><h2 className="font-semibold">{t(status === "waiting" ? "Waiting" : status === "in_progress" ? "In progress" : "Ready")}</h2><span className="rounded-full bg-background px-2 py-0.5 text-sm">{data.tickets.filter((ticket) => ticket.status === status).length}</span></header><div className="space-y-3">{data.tickets.filter((ticket) => ticket.status === status).map((ticket) => <TicketCard key={ticket.id} ticket={ticket} data={data} locale={locale} busy={busy === ticket.id} onTransition={(to) => void transition(ticket, to)} onCollect={(methodId) => void collect(ticket, methodId)} />)}{!data.tickets.some((ticket) => ticket.status === status) ? <p className="rounded-xl border border-dashed bg-background p-5 text-center text-sm text-muted-foreground">{t("No washes here.")}</p> : null}</div></section>)}</div> : null}
	</PageContainer>;
}

function TicketCard({ ticket, data, locale, busy, onTransition, onCollect }: { ticket: Ticket; data: Data; locale: string; busy: boolean; onTransition: (to: string) => void; onCollect: (methodId: string) => void }) {
	const { t } = useI18n(); const [methodId, setMethodId] = useState(data.methods[0]?.id ?? ""); const next = ticket.status === "waiting" ? "in_progress" : ticket.status === "in_progress" ? "ready" : "delivered";
	return <article className="rounded-xl border bg-background p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-medium text-muted-foreground">#{ticket.number}</p><h3 className="font-semibold">{ticket.vehicleDisplay}</h3></div><span className={`rounded-full px-2 py-1 text-xs font-medium ${ticket.paymentStatus === "paid" ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"}`}>{t(ticket.paymentStatus === "paid" ? "Paid" : ticket.paymentStatus === "partial" ? "Partial" : "Unpaid")}</span></div><div className="mt-3 flex items-center justify-between text-sm"><span className="flex items-center gap-1 text-muted-foreground"><Timer className="size-4" />{new Intl.DateTimeFormat(locale, { hour: "2-digit", minute: "2-digit" }).format(new Date(ticket.createdAt))}</span><strong>{formatMoney(ticket.totalMinor, data.currency, locale)}</strong></div>
		{ticket.paymentStatus !== "paid" ? <div className="mt-3 flex gap-2"><select aria-label={t("Payment method")} className="h-9 min-w-0 flex-1 rounded-md border bg-background px-2 text-sm" value={methodId} onChange={(event) => setMethodId(event.target.value)}>{data.methods.map((method) => <option key={method.id} value={method.id}>{method.systemKey === "cash" ? t("Cash") : method.name}</option>)}</select><Button size="sm" variant="outline" disabled={busy || !methodId} onClick={() => onCollect(methodId)}><WalletCards className="size-4" />{t("Collect")}</Button></div> : null}
		<Button className="mt-3 w-full" disabled={busy || (next === "delivered" && ticket.paymentStatus !== "paid")} onClick={() => onTransition(next)}>{t(next === "in_progress" ? "Start wash" : next === "ready" ? "Mark ready" : "Deliver")}</Button>
	</article>;
}

function NewWashForm({ data, onCancel, onCreated }: { data: Data; onCancel: () => void; onCreated: () => Promise<void> }) {
	const { t, locale } = useI18n(); const shell = useAppShell(); const [vehicleTypeId, setVehicleTypeId] = useState(data.vehicleTypes[0]?.id ?? ""); const [plate, setPlate] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [workerId, setWorkerId] = useState(""); const [pending, setPending] = useState(false); const [failed, setFailed] = useState(false);
	const available = useMemo(() => data.services.map((service) => ({ service, price: service.prices.find((price) => price.vehicleTypeId === vehicleTypeId && price.branchId === shell.activeBranch?.id) ?? service.prices.find((price) => price.vehicleTypeId === vehicleTypeId && price.branchId === null) })).filter((row) => row.price), [data.services, vehicleTypeId, shell.activeBranch?.id]);
	const total = available.filter((row) => selected.includes(row.service.id)).reduce((value, row) => value + (row.price?.amountMinor ?? 0), 0);
	async function submit(event: FormEvent) { event.preventDefault(); if (!vehicleTypeId || !selected.length) return; setPending(true); setFailed(false); try { const type = data.vehicleTypes.find((item) => item.id === vehicleTypeId); await washApi.createTicket(shell.organizationId, { vehicleTypeId, plate: plate || null, vehicleDisplay: plate.trim().toUpperCase() || type?.name, lines: selected.map((serviceId) => ({ serviceId, quantity: 1 })), workerIds: workerId ? [workerId] : [] }); await onCreated(); } catch { setFailed(true); } finally { setPending(false); } }
	return <form onSubmit={submit} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-lg font-semibold">{t("New wash")}</h2><p className="text-sm text-muted-foreground">{t("Only the vehicle type and one service are required.")}</p></div><Button type="button" variant="ghost" size="sm" onClick={onCancel}>{t("Cancel")}</Button></div><div className="grid gap-5 lg:grid-cols-[.8fr_1.4fr_.8fr]"><div className="space-y-4"><div className="grid gap-2"><Label htmlFor="vehicle-type">{t("Vehicle type")}</Label><select id="vehicle-type" className="h-10 rounded-md border bg-background px-3" value={vehicleTypeId} onChange={(event) => { setVehicleTypeId(event.target.value); setSelected([]); }}>{data.vehicleTypes.map((type) => <option key={type.id} value={type.id}>{type.systemKey ? t(type.name as "Car") : type.name}</option>)}</select></div><div className="grid gap-2"><Label htmlFor="plate">{t("Plate or description")}</Label><Input id="plate" value={plate} maxLength={30} placeholder={t("Optional")} onChange={(event) => setPlate(event.target.value)} /></div></div><fieldset><legend className="mb-2 text-sm font-medium">{t("Services")}</legend><div className="grid gap-2 sm:grid-cols-2">{available.map(({ service, price }) => <label key={service.id} className={`flex min-h-14 cursor-pointer items-center justify-between gap-3 rounded-xl border p-3 ${selected.includes(service.id) ? "border-primary bg-primary/5" : ""}`}><span><span className="block font-medium">{service.name}</span><span className="text-sm text-muted-foreground">{formatMoney(price!.amountMinor, data.currency, locale)}</span></span><input type="checkbox" checked={selected.includes(service.id)} onChange={() => setSelected((value) => value.includes(service.id) ? value.filter((id) => id !== service.id) : [...value, service.id])} /></label>)}</div>{!available.length ? <p className="text-sm text-muted-foreground">{t("Configure service prices for this vehicle type first.")}</p> : null}</fieldset><div className="space-y-4"><div className="grid gap-2"><Label htmlFor="worker">{t("Worker")}</Label><select id="worker" className="h-10 rounded-md border bg-background px-3" value={workerId} onChange={(event) => setWorkerId(event.target.value)}><option value="">{t("Assign later")}</option>{data.workers.map((worker) => <option key={worker.id} value={worker.id}>{worker.name}</option>)}</select></div><div className="rounded-xl bg-muted p-4"><p className="text-sm text-muted-foreground">{t("Total")}</p><p className="text-2xl font-semibold">{formatMoney(total, data.currency, locale)}</p></div><Button className="w-full" disabled={pending || !selected.length}>{t(pending ? "Adding…" : "Add to queue")}</Button>{failed ? <p role="alert" className="text-sm text-destructive">{t("We could not add the wash.")}</p> : null}</div></div></form>;
}
