import { useEffect, useMemo, useState, type FormEvent } from "react";
import { PageContainer, PageHeader } from "@/components/page";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useAppShell } from "@/hooks/use-app-shell";
import { formatMoney, quantityFromInput, washApi, type InventoryItem, type PaymentMethod } from "@/lib/controlwash";
import { useI18n } from "@/lib/i18n";

export function RetailSalesPage() {
	const { t, locale } = useI18n(); const shell = useAppShell(); const [items, setItems] = useState<InventoryItem[]>([]); const [methods, setMethods] = useState<PaymentMethod[]>([]); const [currency, setCurrency] = useState("COP"); const [itemId, setItemId] = useState(""); const [quantity, setQuantity] = useState("1"); const [methodId, setMethodId] = useState(""); const [pending, setPending] = useState(false); const [feedback, setFeedback] = useState<"saved" | "failed" | null>(null);
	async function load() { const [inventory, payments] = await Promise.all([washApi.items(shell.organizationId), washApi.paymentMethods(shell.organizationId)]); const sellable = inventory.items.filter((item) => item.isActive && item.type !== "supply" && item.priceMinor !== null); setItems(sellable); setCurrency(inventory.currency); setMethods(payments.methods.filter((item) => item.isActive)); setItemId((value) => value || sellable[0]?.id || ""); setMethodId((value) => value || payments.methods.find((item) => item.isActive)?.id || ""); }
	useEffect(() => { let active = true; Promise.all([washApi.items(shell.organizationId), washApi.paymentMethods(shell.organizationId)]).then(([inventory, payments]) => { if (!active) return; const sellable = inventory.items.filter((item) => item.isActive && item.type !== "supply" && item.priceMinor !== null); setItems(sellable); setCurrency(inventory.currency); setMethods(payments.methods.filter((item) => item.isActive)); setItemId(sellable[0]?.id ?? ""); setMethodId(payments.methods.find((item) => item.isActive)?.id ?? ""); }).catch(() => undefined); return () => { active = false; }; }, [shell.organizationId]); const item = useMemo(() => items.find((value) => value.id === itemId), [items, itemId]); const total = Math.round((item?.priceMinor ?? 0) * quantityFromInput(quantity) / 1000);
	async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setFeedback(null); try { await washApi.createSale(shell.organizationId, { paymentMethodId: methodId, lines: [{ itemId, quantityMilli: quantityFromInput(quantity) }] }); setFeedback("saved"); setQuantity("1"); await load(); } catch { setFeedback("failed"); } finally { setPending(false); } }
	return <PageContainer><PageHeader title={t("Quick sale")} description={t("Sell water, drinks or accessories in a few taps.")} /><form onSubmit={submit} className="mx-auto max-w-2xl rounded-3xl border p-6 shadow-sm"><div className="grid gap-5"><div className="grid gap-2"><Label>{t("Product")}</Label><select className="h-12 rounded-xl border bg-background px-3" value={itemId} onChange={(event) => setItemId(event.target.value)}>{items.map((value) => <option key={value.id} value={value.id}>{value.name} · {(value.quantityMilli / 1000).toLocaleString(locale)} {value.unit}</option>)}</select></div><div className="grid grid-cols-2 gap-4"><div className="grid gap-2"><Label>{t("Quantity")}</Label><Input className="h-12" inputMode="decimal" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></div><div className="grid gap-2"><Label>{t("Payment method")}</Label><select className="h-12 rounded-xl border bg-background px-3" value={methodId} onChange={(event) => setMethodId(event.target.value)}>{methods.map((method) => <option key={method.id} value={method.id}>{method.systemKey === "cash" ? t("Cash") : method.name}</option>)}</select></div></div><div className="rounded-2xl bg-primary p-5 text-primary-foreground"><p className="text-sm opacity-80">{t("Total to collect")}</p><p className="text-3xl font-semibold">{formatMoney(total, currency, locale)}</p></div>{feedback ? <p role={feedback === "failed" ? "alert" : "status"} className="text-sm">{t(feedback === "saved" ? "Sale recorded." : "We could not record the sale.")}</p> : null}<Button className="h-12" disabled={pending || !itemId || !methodId || total <= 0}>{t(pending ? "Saving…" : "Record sale")}</Button></div></form>{!items.length ? <p className="mt-6 text-center text-muted-foreground">{t("Create a product with a sale price in Inventory first.")}</p> : null}</PageContainer>;
}
