import { useEffect, useState, type FormEvent } from "react";
import { PageContainer, PageHeader } from "@/components/page";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useAppShell } from "@/hooks/use-app-shell";
import { amountFromInput, formatMoney, washApi, type Service, type VehicleType } from "@/lib/controlwash";
import { useI18n } from "@/lib/i18n";

export function ServicesPage() {
	const { t, locale } = useI18n(); const shell = useAppShell(); const [services, setServices] = useState<Service[]>([]); const [types, setTypes] = useState<VehicleType[]>([]); const [currency, setCurrency] = useState("COP"); const [creating, setCreating] = useState(false); const [editing, setEditing] = useState<Service | null>(null); const [failed, setFailed] = useState(false);
	async function load() { setFailed(false); try { const [serviceData, typeData, settings] = await Promise.all([washApi.services(shell.organizationId), washApi.vehicleTypes(shell.organizationId), washApi.balances(shell.organizationId)]); setServices(serviceData.services); setTypes(typeData.vehicleTypes.filter((item) => item.isActive)); setCurrency(settings.currency); } catch { setFailed(true); } }
	useEffect(() => { let active = true; Promise.all([washApi.services(shell.organizationId), washApi.vehicleTypes(shell.organizationId), washApi.balances(shell.organizationId)]).then(([serviceData, typeData, settings]) => { if (active) { setServices(serviceData.services); setTypes(typeData.vehicleTypes.filter((item) => item.isActive)); setCurrency(settings.currency); } }).catch(() => { if (active) setFailed(true); }); return () => { active = false; }; }, [shell.organizationId]);
	return <PageContainer className="space-y-6"><PageHeader title={t("Services and prices")} description={t("Create services, packages or add-ons and set a price for each vehicle type.")} actions={<Button onClick={() => setCreating(true)}>{t("New service")}</Button>} />{failed ? <p role="alert">{t("We could not load services.")}</p> : null}{creating ? <ServiceForm onCancel={() => setCreating(false)} onSaved={async (service) => { setCreating(false); setEditing(service); await load(); }} /> : null}{editing ? <PriceForm service={editing} types={types} currency={currency} onCancel={() => setEditing(null)} onSaved={async () => { setEditing(null); await load(); }} /> : null}<div className="grid gap-3 sm:grid-cols-2">{services.map((service) => <article key={service.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between"><div><h2 className="font-semibold">{service.name}</h2><p className="text-sm text-muted-foreground">{t(service.kind === "service" ? "Service" : service.kind === "package" ? "Package" : "Add-on")}</p></div><span className="text-sm text-muted-foreground">{t(service.isActive ? "Active" : "Inactive")}</span></div><div className="mt-4 flex flex-wrap gap-2">{types.map((type) => { const price = service.prices.find((item) => item.vehicleTypeId === type.id && (item.branchId === shell.activeBranch?.id || item.branchId === null)); return <span key={type.id} className="rounded-full bg-muted px-3 py-1 text-sm">{type.name}: {price ? formatMoney(price.amountMinor, currency, locale) : "—"}</span>; })}</div><Button className="mt-4" size="sm" variant="outline" onClick={() => setEditing(service)}>{t("Edit prices")}</Button></article>)}</div></PageContainer>;
}

function ServiceForm({ onCancel, onSaved }: { onCancel: () => void; onSaved: (service: Service) => Promise<void> }) { const { t } = useI18n(); const shell = useAppShell(); const [name, setName] = useState(""); const [kind, setKind] = useState("service"); const [duration, setDuration] = useState(""); const [failed, setFailed] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setFailed(false); try { await onSaved(await washApi.createService(shell.organizationId, { name, kind, durationMinutes: duration ? Number(duration) : null })); } catch { setFailed(true); } } return <form onSubmit={submit} className="rounded-2xl border p-5"><div className="mb-4 flex justify-between"><h2 className="font-semibold">{t("New service")}</h2><Button type="button" variant="ghost" onClick={onCancel}>{t("Cancel")}</Button></div><div className="grid gap-4 sm:grid-cols-3"><div className="grid gap-2"><Label>{t("Name")}</Label><Input value={name} required onChange={(event) => setName(event.target.value)} /></div><div className="grid gap-2"><Label>{t("Type")}</Label><select className="h-10 rounded-md border bg-background px-3" value={kind} onChange={(event) => setKind(event.target.value)}><option value="service">{t("Service")}</option><option value="package">{t("Package")}</option><option value="addon">{t("Add-on")}</option></select></div><div className="grid gap-2"><Label>{t("Estimated minutes")}</Label><Input inputMode="numeric" value={duration} onChange={(event) => setDuration(event.target.value)} /></div></div>{failed ? <p role="alert" className="mt-3 text-sm text-destructive">{t("We could not save the service.")}</p> : null}<Button className="mt-4">{t("Continue to prices")}</Button></form>; }

function PriceForm({ service, types, currency, onCancel, onSaved }: { service: Service; types: VehicleType[]; currency: string; onCancel: () => void; onSaved: () => Promise<void> }) { const { t } = useI18n(); const shell = useAppShell(); const [prices, setPrices] = useState<Record<string, string>>(() => Object.fromEntries(types.map((type) => [type.id, String((service.prices.find((price) => price.vehicleTypeId === type.id && price.branchId === null)?.amountMinor ?? 0) / 100 || "")]))); const [failed, setFailed] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setFailed(false); try { await washApi.replacePrices(shell.organizationId, service.id, { prices: types.filter((type) => prices[type.id]).map((type) => ({ vehicleTypeId: type.id, branchId: null, amountMinor: amountFromInput(prices[type.id]!) })) }); await onSaved(); } catch { setFailed(true); } } return <form onSubmit={submit} className="rounded-2xl border p-5"><div className="mb-4 flex justify-between"><div><h2 className="font-semibold">{t("Prices for {name}", { name: service.name })}</h2><p className="text-sm text-muted-foreground">{currency}</p></div><Button type="button" variant="ghost" onClick={onCancel}>{t("Cancel")}</Button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{types.map((type) => <div key={type.id} className="grid gap-2"><Label>{type.name}</Label><Input inputMode="numeric" placeholder="20000" value={prices[type.id] ?? ""} onChange={(event) => setPrices({ ...prices, [type.id]: event.target.value })} /></div>)}</div>{failed ? <p role="alert" className="mt-3 text-sm text-destructive">{t("We could not save prices.")}</p> : null}<Button className="mt-4">{t("Save prices")}</Button></form>; }
