import { useEffect, useState, type FormEvent } from "react";
import { PageContainer, PageHeader } from "@/components/page";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useAppShell } from "@/hooks/use-app-shell";
import { washApi, type CommissionRule, type Service, type Worker } from "@/lib/controlwash";
import { useI18n } from "@/lib/i18n";

export function WorkersPage() {
	const { t } = useI18n(); const shell = useAppShell(); const [workers, setWorkers] = useState<Worker[]>([]); const [rules, setRules] = useState<CommissionRule[]>([]); const [services, setServices] = useState<Service[]>([]); const [mode, setMode] = useState<"worker" | "rule" | null>(null); const [failed, setFailed] = useState(false);
	async function load() { setFailed(false); try { const [workerData, serviceData] = await Promise.all([washApi.workers(shell.organizationId), washApi.services(shell.organizationId)]); setWorkers(workerData.workers); setRules(workerData.rules); setServices(serviceData.services.filter((item) => item.isActive)); } catch { setFailed(true); } }
	useEffect(() => { let active = true; Promise.all([washApi.workers(shell.organizationId), washApi.services(shell.organizationId)]).then(([workerData, serviceData]) => { if (active) { setWorkers(workerData.workers); setRules(workerData.rules); setServices(serviceData.services.filter((item) => item.isActive)); } }).catch(() => { if (active) setFailed(true); }); return () => { active = false; }; }, [shell.organizationId]);
	return <PageContainer className="space-y-6"><PageHeader title={t("Workers and commissions")} description={t("Assign washes and keep transparent commission estimates.")} actions={<div className="flex gap-2"><Button variant="outline" onClick={() => setMode("rule")}>{t("Commission rule")}</Button><Button onClick={() => setMode("worker")}>{t("Add worker")}</Button></div>} />{failed ? <p role="alert">{t("We could not load workers.")}</p> : null}{mode ? <WorkerForm mode={mode} workers={workers} services={services} onCancel={() => setMode(null)} onSaved={async () => { setMode(null); await load(); }} /> : null}<div className="grid gap-5 lg:grid-cols-2"><section><h2 className="mb-3 text-lg font-semibold">{t("Workers")}</h2><div className="grid gap-3">{workers.map((worker) => <div key={worker.id} className="rounded-2xl border p-4"><div className="flex justify-between"><div><p className="font-medium">{worker.name}</p><p className="text-sm text-muted-foreground">{worker.phone || t("No phone")}</p></div><span className="text-sm text-muted-foreground">{t(worker.isActive ? "Active" : "Inactive")}</span></div></div>)}</div></section><section><h2 className="mb-3 text-lg font-semibold">{t("Commission rules")}</h2><div className="grid gap-3">{rules.map((rule) => <div key={rule.id} className="rounded-2xl border p-4"><p className="font-medium">{(rule.percentageBasisPoints / 100).toLocaleString()}%</p><p className="text-sm text-muted-foreground">{workers.find((worker) => worker.id === rule.workerId)?.name ?? t("All workers")} · {services.find((service) => service.id === rule.serviceId)?.name ?? t("All services")}</p></div>)}{!rules.length ? <p className="text-muted-foreground">{t("No commission rules yet.")}</p> : null}</div></section></div></PageContainer>;
}

function WorkerForm({ mode, workers, services, onCancel, onSaved }: { mode: "worker" | "rule"; workers: Worker[]; services: Service[]; onCancel: () => void; onSaved: () => Promise<void> }) {
	const { t } = useI18n(); const shell = useAppShell(); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [workerId, setWorkerId] = useState(""); const [serviceId, setServiceId] = useState(""); const [percentage, setPercentage] = useState(""); const [pending, setPending] = useState(false); const [failed, setFailed] = useState(false);
	async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setFailed(false); try { if (mode === "worker") await washApi.createWorker(shell.organizationId, { name, phone: phone || null }); else await washApi.createCommissionRule(shell.organizationId, { workerId: workerId || null, serviceId: serviceId || null, branchId: shell.activeBranch?.id ?? null, percentageBasisPoints: Math.round(Number(percentage.replace(",", ".")) * 100) }); await onSaved(); } catch { setFailed(true); } finally { setPending(false); } }
	return <form onSubmit={submit} className="rounded-2xl border p-5"><div className="mb-4 flex justify-between"><h2 className="font-semibold">{t(mode === "worker" ? "Add worker" : "Commission rule")}</h2><Button type="button" variant="ghost" onClick={onCancel}>{t("Cancel")}</Button></div><div className="grid gap-4 sm:grid-cols-2">{mode === "worker" ? <><div className="grid gap-2"><Label>{t("Name")}</Label><Input value={name} required onChange={(event) => setName(event.target.value)} /></div><div className="grid gap-2"><Label>{t("Phone")}</Label><Input value={phone} onChange={(event) => setPhone(event.target.value)} /></div></> : <><div className="grid gap-2"><Label>{t("Worker")}</Label><select className="h-10 rounded-md border bg-background px-3" value={workerId} onChange={(event) => setWorkerId(event.target.value)}><option value="">{t("All workers")}</option>{workers.filter((worker) => worker.isActive).map((worker) => <option key={worker.id} value={worker.id}>{worker.name}</option>)}</select></div><div className="grid gap-2"><Label>{t("Service")}</Label><select className="h-10 rounded-md border bg-background px-3" value={serviceId} onChange={(event) => setServiceId(event.target.value)}><option value="">{t("All services")}</option>{services.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select></div><div className="grid gap-2"><Label>{t("Percentage")}</Label><Input inputMode="decimal" value={percentage} required placeholder="20" onChange={(event) => setPercentage(event.target.value)} /></div></>}</div>{failed ? <p role="alert" className="mt-3 text-sm text-destructive">{t("We could not save the worker configuration.")}</p> : null}<Button className="mt-4" disabled={pending}>{t(pending ? "Saving…" : "Save")}</Button></form>;
}
