import { and, asc, desc, eq, inArray, sum } from "drizzle-orm";
import { AuthError } from "../auth/session";
import { getTenantDb } from "../db";
import { auditEvent, financialMovement, idempotencyRecord, inventoryItem, payment, paymentMethod, productSettings, purchase, purchaseLine, retailSale, retailSaleLine, stockMovement, washTicket } from "../db/schema";
import { RequestError } from "../http";
import { canAccessBranch } from "../tenant/branch";
import { assertKeys, auditValues, booleanValue, idempotencyValues, integerValue, normalizeName, readIdempotency, requireManager, requireProductContext, textValue } from "./domain";

type ItemLine = { itemId: string; quantityMilli: number; unitAmountMinor: number | null };
function parseItemLines(value: unknown, amountKey: string): ItemLine[] {
	if (!Array.isArray(value) || value.length === 0 || value.length > 100) throw new RequestError(400, "INVALID_LINES");
	return value.map((raw) => {
		if (!raw || typeof raw !== "object" || Array.isArray(raw)) throw new RequestError(400, "INVALID_LINES"); const line = raw as Record<string, unknown>;
		assertKeys(line, ["itemId", "quantityMilli", amountKey]);
		return { itemId: textValue(line.itemId)!, quantityMilli: integerValue(line.quantityMilli, "INVALID_QUANTITY", 1), unitAmountMinor: line[amountKey] === undefined || line[amountKey] === null ? null : integerValue(line[amountKey], "INVALID_AMOUNT") };
	});
}

async function stockBalances(env: Env, organizationId: string, branchId: string, itemIds?: string[]) {
	const db = getTenantDb(env, organizationId); const condition = and(eq(stockMovement.organizationId, organizationId), eq(stockMovement.branchId, branchId), itemIds?.length ? inArray(stockMovement.itemId, itemIds) : undefined);
	return await db.select({ itemId: stockMovement.itemId, quantityMilli: sum(stockMovement.quantityMilli) }).from(stockMovement).where(condition).groupBy(stockMovement.itemId);
}

export async function listItems(env: Env, request: Request) {
	const context = await requireProductContext(env, request); const db = getTenantDb(env, context.tenant.organizationId);
	const items = await db.select().from(inventoryItem).where(eq(inventoryItem.organizationId, context.tenant.organizationId)).orderBy(asc(inventoryItem.name)); const balances = await stockBalances(env, context.tenant.organizationId, context.branch.branchId);
	return { items: items.map((item) => ({ ...item, quantityMilli: Number(balances.find((balance) => balance.itemId === item.id)?.quantityMilli ?? 0) })), currency: context.currency, canEdit: context.tenant.organizationRole === "owner" || context.tenant.organizationRole === "admin" };
}

export async function getItem(env: Env, request: Request, id: string) { const items = await listItems(env, request); const item = items.items.find((value) => value.id === id); if (!item) throw new AuthError(404, "RESOURCE_NOT_FOUND"); return item; }

export async function listStock(env: Env, request: Request) { const result = await listItems(env, request); return { currency: result.currency, stock: result.items.map((item) => ({ itemId: item.id, name: item.name, unit: item.unit, quantityMilli: item.quantityMilli, lowStockMilli: item.lowStockMilli, isLow: item.quantityMilli <= item.lowStockMilli })) }; }

export async function createItem(env: Env, request: Request, body: Record<string, unknown>) {
	const context = await requireProductContext(env, request); requireManager(context.tenant); assertKeys(body, ["name", "type", "unit", "costMinor", "priceMinor", "lowStockMilli"]);
	const name = textValue(body.name)!; const type = body.type ?? "supply"; if (!["supply", "retail", "both"].includes(String(type))) throw new RequestError(400, "INVALID_ITEM_TYPE");
	const id = crypto.randomUUID(); const values = { id, organizationId: context.tenant.organizationId, name, normalizedName: normalizeName(name), type: String(type), unit: textValue(body.unit, "INVALID_UNIT", 30, true) ?? "unit", costMinor: body.costMinor === undefined ? 0 : integerValue(body.costMinor, "INVALID_AMOUNT"), priceMinor: body.priceMinor === undefined || body.priceMinor === null ? null : integerValue(body.priceMinor, "INVALID_AMOUNT"), lowStockMilli: body.lowStockMilli === undefined ? 0 : integerValue(body.lowStockMilli, "INVALID_QUANTITY"), createdByUserId: context.tenant.userId };
	await getTenantDb(env, context.tenant.organizationId).insert(inventoryItem).values(values); return { ...values, isActive: true, quantityMilli: 0 };
}

export async function updateItem(env: Env, request: Request, id: string, body: Record<string, unknown>) {
	const context = await requireProductContext(env, request); requireManager(context.tenant); assertKeys(body, ["name", "type", "unit", "costMinor", "priceMinor", "lowStockMilli", "isActive"]); const db = getTenantDb(env, context.tenant.organizationId);
	const [current] = await db.select().from(inventoryItem).where(and(eq(inventoryItem.id, id), eq(inventoryItem.organizationId, context.tenant.organizationId))).limit(1); if (!current) throw new AuthError(404, "RESOURCE_NOT_FOUND");
	const name = body.name === undefined ? current.name : textValue(body.name)!; const type = body.type === undefined ? current.type : String(body.type); if (!["supply", "retail", "both"].includes(type)) throw new RequestError(400, "INVALID_ITEM_TYPE");
	const unit = body.unit === undefined ? current.unit : textValue(body.unit, "INVALID_UNIT", 30)!; if (unit !== current.unit) { const [movement] = await db.select({ id: stockMovement.id }).from(stockMovement).where(and(eq(stockMovement.organizationId, context.tenant.organizationId), eq(stockMovement.itemId, id))).limit(1); if (movement) throw new RequestError(409, "ITEM_UNIT_LOCKED"); }
	const values = { name, normalizedName: normalizeName(name), type, unit, costMinor: body.costMinor === undefined ? current.costMinor : integerValue(body.costMinor, "INVALID_AMOUNT"), priceMinor: body.priceMinor === undefined ? current.priceMinor : body.priceMinor === null ? null : integerValue(body.priceMinor, "INVALID_AMOUNT"), lowStockMilli: body.lowStockMilli === undefined ? current.lowStockMilli : integerValue(body.lowStockMilli, "INVALID_QUANTITY"), isActive: body.isActive === undefined ? current.isActive : booleanValue(body.isActive), updatedAt: new Date() };
	await db.update(inventoryItem).set(values).where(and(eq(inventoryItem.id, id), eq(inventoryItem.organizationId, context.tenant.organizationId))); return { ...current, ...values };
}

export async function createStockMovement(env: Env, request: Request, body: Record<string, unknown>, kind: "opening" | "usage" | "adjustment") {
	const context = await requireProductContext(env, request); if (kind !== "usage") requireManager(context.tenant); assertKeys(body, ["itemId", "quantityMilli", "description", "reason"]);
	const idempotency = await readIdempotency(env, request, context.tenant, `stock.${kind}`, body); if (idempotency.replay) return idempotency.replay;
	const itemId = textValue(body.itemId)!; const db = getTenantDb(env, context.tenant.organizationId); const [item] = await db.select().from(inventoryItem).where(and(eq(inventoryItem.id, itemId), eq(inventoryItem.organizationId, context.tenant.organizationId), eq(inventoryItem.isActive, true))).limit(1); if (!item) throw new RequestError(400, "INVALID_ITEM");
	let quantityMilli = integerValue(Math.abs(Number(body.quantityMilli)), "INVALID_QUANTITY", 1) * (Number(body.quantityMilli) < 0 ? -1 : 1); if (kind === "usage") quantityMilli = -Math.abs(quantityMilli); if (kind === "opening") quantityMilli = Math.abs(quantityMilli);
	const reason = kind === "opening" ? textValue(body.reason, "INVALID_REASON", 300, true) : textValue(body.reason, "REASON_REQUIRED", 300)!; const description = textValue(body.description, "INVALID_DESCRIPTION", 200, true) ?? (kind === "usage" ? "Manual usage" : kind === "opening" ? "Opening stock" : "Stock adjustment");
	if (quantityMilli < 0) await enforceStock(env, context.tenant.organizationId, context.branch.branchId, [{ itemId, quantityMilli: Math.abs(quantityMilli), unitAmountMinor: null }]);
	const id = crypto.randomUUID(); const response = { id, itemId, itemName: item.name, quantityMilli, kind, description };
	await db.batch([db.insert(stockMovement).values({ id, organizationId: context.tenant.organizationId, branchId: context.branch.branchId, itemId, kind, quantityMilli, unitCostMinor: item.costMinor, description, sourceType: kind, sourceId: id, createdByUserId: context.tenant.userId }), db.insert(auditEvent).values(auditValues(context, `stock.${kind}`, "stock_movement", id, reason, { quantityMilli })), db.insert(idempotencyRecord).values(idempotencyValues(context.tenant, `stock.${kind}`, idempotency, id, response))]); return response;
}

async function activePaymentMethod(env: Env, organizationId: string, id: string) { return (await getTenantDb(env, organizationId).select().from(paymentMethod).where(and(eq(paymentMethod.id, id), eq(paymentMethod.organizationId, organizationId), eq(paymentMethod.isActive, true))).limit(1))[0] ?? null; }

async function enforceStock(env: Env, organizationId: string, branchId: string, lines: ItemLine[]) {
	const db = getTenantDb(env, organizationId); const balances = await stockBalances(env, organizationId, branchId, lines.map((line) => line.itemId)); const [settings] = await db.select().from(productSettings).where(eq(productSettings.organizationId, organizationId)).limit(1);
	if (settings?.negativeStockPolicy === "strict" && lines.some((line) => Number(balances.find((balance) => balance.itemId === line.itemId)?.quantityMilli ?? 0) < line.quantityMilli)) throw new RequestError(409, "INSUFFICIENT_STOCK");
}

export async function listPurchases(env: Env, request: Request) { const context = await requireProductContext(env, request); return { purchases: await getTenantDb(env, context.tenant.organizationId).select().from(purchase).where(and(eq(purchase.organizationId, context.tenant.organizationId), eq(purchase.branchId, context.branch.branchId))).orderBy(desc(purchase.createdAt)).limit(200) }; }

export async function getPurchase(env: Env, request: Request, id: string) { const context = await requireProductContext(env, request); const db = getTenantDb(env, context.tenant.organizationId); const [document] = await db.select().from(purchase).where(and(eq(purchase.id, id), eq(purchase.organizationId, context.tenant.organizationId), eq(purchase.branchId, context.branch.branchId))).limit(1); if (!document) throw new AuthError(404, "RESOURCE_NOT_FOUND"); return { purchase: document, lines: await db.select().from(purchaseLine).where(eq(purchaseLine.purchaseId, id)) }; }

export async function createPurchase(env: Env, request: Request, body: Record<string, unknown>) {
	const context = await requireProductContext(env, request); assertKeys(body, ["paymentMethodId", "supplier", "lines"]); const idempotency = await readIdempotency(env, request, context.tenant, "purchase.create", body); if (idempotency.replay) return idempotency.replay;
	const paymentMethodId = textValue(body.paymentMethodId)!; const method = await activePaymentMethod(env, context.tenant.organizationId, paymentMethodId); if (!method) throw new RequestError(400, "INVALID_PAYMENT_METHOD"); const lines = parseItemLines(body.lines, "unitCostMinor"); const db = getTenantDb(env, context.tenant.organizationId);
	const items = await db.select().from(inventoryItem).where(and(eq(inventoryItem.organizationId, context.tenant.organizationId), eq(inventoryItem.isActive, true), inArray(inventoryItem.id, lines.map((line) => line.itemId)))); if (items.length !== new Set(lines.map((line) => line.itemId)).size) throw new RequestError(400, "INVALID_ITEM");
	const rows = lines.map((line) => { const item = items.find((value) => value.id === line.itemId)!; const unitCostMinor = line.unitAmountMinor ?? item.costMinor; return { id: crypto.randomUUID(), purchaseId: "", itemId: item.id, itemName: item.name, quantityMilli: line.quantityMilli, unitCostMinor, totalMinor: Math.round(line.quantityMilli * unitCostMinor / 1000) }; });
	const totalMinor = rows.reduce((total, line) => total + line.totalMinor, 0); const id = crypto.randomUUID(); rows.forEach((line) => { line.purchaseId = id; }); const response = { id, paymentMethodId, supplier: textValue(body.supplier, "INVALID_SUPPLIER", 160, true), totalMinor, currency: context.currency, status: "posted", lines: rows };
	await db.batch([db.insert(purchase).values({ id, organizationId: context.tenant.organizationId, branchId: context.branch.branchId, paymentMethodId, supplier: response.supplier, totalMinor, currency: context.currency, createdByUserId: context.tenant.userId }), ...rows.map((line) => db.insert(purchaseLine).values(line)), ...rows.map((line) => db.insert(stockMovement).values({ id: crypto.randomUUID(), organizationId: context.tenant.organizationId, branchId: context.branch.branchId, itemId: line.itemId, kind: "purchase", quantityMilli: line.quantityMilli, unitCostMinor: line.unitCostMinor, description: `Purchase: ${line.itemName}`, sourceType: "purchase", sourceId: id, createdByUserId: context.tenant.userId })), db.insert(financialMovement).values({ id: crypto.randomUUID(), organizationId: context.tenant.organizationId, branchId: context.branch.branchId, paymentMethodId, kind: "purchase", amountMinor: -totalMinor, currency: context.currency, description: response.supplier ? `Purchase from ${response.supplier}` : "Stock purchase", sourceType: "purchase", sourceId: id, createdByUserId: context.tenant.userId }), db.insert(auditEvent).values(auditValues(context, "purchase.posted", "purchase", id, null, { totalMinor })), db.insert(idempotencyRecord).values(idempotencyValues(context.tenant, "purchase.create", idempotency, id, response))]); return response;
}

export async function reversePurchase(env: Env, request: Request, id: string, body: Record<string, unknown>) {
	const context = await requireProductContext(env, request); requireManager(context.tenant); assertKeys(body, ["reason"]); const reason = textValue(body.reason, "REASON_REQUIRED", 300)!;
	const idempotency = await readIdempotency(env, request, context.tenant, `purchase.reverse.${id}`, body); if (idempotency.replay) return idempotency.replay; const db = getTenantDb(env, context.tenant.organizationId);
	const [original] = await db.select().from(purchase).where(and(eq(purchase.id, id), eq(purchase.organizationId, context.tenant.organizationId), eq(purchase.branchId, context.branch.branchId))).limit(1); if (!original || original.totalMinor < 0) throw new AuthError(404, "RESOURCE_NOT_FOUND");
	const [already] = await db.select({ id: purchase.id }).from(purchase).where(eq(purchase.reversalOfId, id)).limit(1); if (already) throw new RequestError(409, "ALREADY_REVERSED"); const lines = await db.select().from(purchaseLine).where(eq(purchaseLine.purchaseId, id)); await enforceStock(env, context.tenant.organizationId, context.branch.branchId, lines.map((line) => ({ itemId: line.itemId, quantityMilli: line.quantityMilli, unitAmountMinor: line.unitCostMinor })));
	const reversalId = crypto.randomUUID(); const response = { id: reversalId, reversalOfId: id, totalMinor: -original.totalMinor, status: "reversed" };
	await db.batch([db.insert(purchase).values({ id: reversalId, organizationId: context.tenant.organizationId, branchId: context.branch.branchId, paymentMethodId: original.paymentMethodId, supplier: original.supplier, totalMinor: -original.totalMinor, currency: original.currency, status: "reversed", reversalOfId: id, reason, createdByUserId: context.tenant.userId }), ...lines.map((line) => db.insert(stockMovement).values({ id: crypto.randomUUID(), organizationId: context.tenant.organizationId, branchId: context.branch.branchId, itemId: line.itemId, kind: "purchase_reversal", quantityMilli: -line.quantityMilli, unitCostMinor: line.unitCostMinor, description: `Purchase reversal: ${line.itemName}`, sourceType: "purchase", sourceId: reversalId, reversalOfId: id, createdByUserId: context.tenant.userId })), db.insert(financialMovement).values({ id: crypto.randomUUID(), organizationId: context.tenant.organizationId, branchId: context.branch.branchId, paymentMethodId: original.paymentMethodId, kind: "purchase_reversal", amountMinor: original.totalMinor, currency: original.currency, description: "Purchase reversal", sourceType: "purchase", sourceId: reversalId, reversalOfId: id, createdByUserId: context.tenant.userId }), db.insert(auditEvent).values(auditValues(context, "purchase.reversed", "purchase", id, reason)), db.insert(idempotencyRecord).values(idempotencyValues(context.tenant, `purchase.reverse.${id}`, idempotency, reversalId, response))]); return response;
}

export async function listSales(env: Env, request: Request) { const context = await requireProductContext(env, request); return { sales: await getTenantDb(env, context.tenant.organizationId).select().from(retailSale).where(and(eq(retailSale.organizationId, context.tenant.organizationId), eq(retailSale.branchId, context.branch.branchId))).orderBy(desc(retailSale.createdAt)).limit(200) }; }

export async function getSale(env: Env, request: Request, id: string) { const context = await requireProductContext(env, request); const db = getTenantDb(env, context.tenant.organizationId); const [document] = await db.select().from(retailSale).where(and(eq(retailSale.id, id), eq(retailSale.organizationId, context.tenant.organizationId), eq(retailSale.branchId, context.branch.branchId))).limit(1); if (!document) throw new AuthError(404, "RESOURCE_NOT_FOUND"); return { sale: document, lines: await db.select().from(retailSaleLine).where(eq(retailSaleLine.saleId, id)) }; }

export async function createSale(env: Env, request: Request, body: Record<string, unknown>) {
	const context = await requireProductContext(env, request); assertKeys(body, ["paymentMethodId", "ticketId", "lines"]); const idempotency = await readIdempotency(env, request, context.tenant, "sale.create", body); if (idempotency.replay) return idempotency.replay;
	const paymentMethodId = textValue(body.paymentMethodId)!; const method = await activePaymentMethod(env, context.tenant.organizationId, paymentMethodId); if (!method) throw new RequestError(400, "INVALID_PAYMENT_METHOD"); const lines = parseItemLines(body.lines, "unitPriceMinor"); const db = getTenantDb(env, context.tenant.organizationId);
	const items = await db.select().from(inventoryItem).where(and(eq(inventoryItem.organizationId, context.tenant.organizationId), eq(inventoryItem.isActive, true), inArray(inventoryItem.id, lines.map((line) => line.itemId)))); if (items.length !== new Set(lines.map((line) => line.itemId)).size || items.some((item) => item.type === "supply")) throw new RequestError(400, "INVALID_ITEM"); await enforceStock(env, context.tenant.organizationId, context.branch.branchId, lines);
	const ticketId = textValue(body.ticketId, "INVALID_TICKET", 100, true); if (ticketId) { const [ticket] = await db.select({ id: washTicket.id }).from(washTicket).where(and(eq(washTicket.id, ticketId), eq(washTicket.organizationId, context.tenant.organizationId), eq(washTicket.branchId, context.branch.branchId))).limit(1); if (!ticket) throw new RequestError(400, "INVALID_TICKET"); }
	const rows = lines.map((line) => { const item = items.find((value) => value.id === line.itemId)!; const unitPriceMinor = line.unitAmountMinor ?? item.priceMinor; if (unitPriceMinor === null) throw new RequestError(400, "PRICE_NOT_AVAILABLE"); return { id: crypto.randomUUID(), saleId: "", itemId: item.id, itemName: item.name, quantityMilli: line.quantityMilli, unitPriceMinor, totalMinor: Math.round(line.quantityMilli * unitPriceMinor / 1000) }; });
	const totalMinor = rows.reduce((total, line) => total + line.totalMinor, 0); const id = crypto.randomUUID(); rows.forEach((line) => { line.saleId = id; }); const response = { id, ticketId, paymentMethodId, totalMinor, currency: context.currency, status: "posted", lines: rows };
	await db.batch([db.insert(retailSale).values({ id, organizationId: context.tenant.organizationId, branchId: context.branch.branchId, ticketId, paymentMethodId, totalMinor, currency: context.currency, createdByUserId: context.tenant.userId }), ...rows.map((line) => db.insert(retailSaleLine).values(line)), ...rows.map((line) => db.insert(stockMovement).values({ id: crypto.randomUUID(), organizationId: context.tenant.organizationId, branchId: context.branch.branchId, itemId: line.itemId, kind: "sale", quantityMilli: -line.quantityMilli, unitCostMinor: items.find((item) => item.id === line.itemId)!.costMinor, description: `Sale: ${line.itemName}`, sourceType: "sale", sourceId: id, createdByUserId: context.tenant.userId })), db.insert(payment).values({ id: crypto.randomUUID(), organizationId: context.tenant.organizationId, branchId: context.branch.branchId, saleId: id, paymentMethodId, amountMinor: totalMinor, currency: context.currency, createdByUserId: context.tenant.userId }), db.insert(financialMovement).values({ id: crypto.randomUUID(), organizationId: context.tenant.organizationId, branchId: context.branch.branchId, paymentMethodId, kind: "retail_income", amountMinor: totalMinor, currency: context.currency, description: "Quick sale", sourceType: "sale", sourceId: id, createdByUserId: context.tenant.userId }), db.insert(auditEvent).values(auditValues(context, "sale.posted", "retail_sale", id, null, { totalMinor })), db.insert(idempotencyRecord).values(idempotencyValues(context.tenant, "sale.create", idempotency, id, response))]); return response;
}

export async function reverseSale(env: Env, request: Request, id: string, body: Record<string, unknown>) {
	const context = await requireProductContext(env, request); requireManager(context.tenant); assertKeys(body, ["reason"]); const reason = textValue(body.reason, "REASON_REQUIRED", 300)!;
	const idempotency = await readIdempotency(env, request, context.tenant, `sale.reverse.${id}`, body); if (idempotency.replay) return idempotency.replay; const db = getTenantDb(env, context.tenant.organizationId);
	const [original] = await db.select().from(retailSale).where(and(eq(retailSale.id, id), eq(retailSale.organizationId, context.tenant.organizationId), eq(retailSale.branchId, context.branch.branchId))).limit(1); if (!original || original.totalMinor < 0) throw new AuthError(404, "RESOURCE_NOT_FOUND"); const [already] = await db.select({ id: retailSale.id }).from(retailSale).where(eq(retailSale.reversalOfId, id)).limit(1); if (already) throw new RequestError(409, "ALREADY_REVERSED"); const lines = await db.select().from(retailSaleLine).where(eq(retailSaleLine.saleId, id)); const reversalId = crypto.randomUUID(); const response = { id: reversalId, reversalOfId: id, totalMinor: -original.totalMinor, status: "reversed" };
	await db.batch([db.insert(retailSale).values({ id: reversalId, organizationId: context.tenant.organizationId, branchId: context.branch.branchId, ticketId: original.ticketId, paymentMethodId: original.paymentMethodId, totalMinor: -original.totalMinor, currency: original.currency, status: "reversed", reversalOfId: id, reason, createdByUserId: context.tenant.userId }), ...lines.map((line) => db.insert(stockMovement).values({ id: crypto.randomUUID(), organizationId: context.tenant.organizationId, branchId: context.branch.branchId, itemId: line.itemId, kind: "sale_reversal", quantityMilli: line.quantityMilli, unitCostMinor: 0, description: `Sale reversal: ${line.itemName}`, sourceType: "sale", sourceId: reversalId, reversalOfId: id, createdByUserId: context.tenant.userId })), db.insert(payment).values({ id: crypto.randomUUID(), organizationId: context.tenant.organizationId, branchId: context.branch.branchId, saleId: reversalId, paymentMethodId: original.paymentMethodId, amountMinor: -original.totalMinor, currency: original.currency, status: "reversed", reversalOfId: id, reason, createdByUserId: context.tenant.userId }), db.insert(financialMovement).values({ id: crypto.randomUUID(), organizationId: context.tenant.organizationId, branchId: context.branch.branchId, paymentMethodId: original.paymentMethodId, kind: "retail_reversal", amountMinor: -original.totalMinor, currency: original.currency, description: "Quick sale reversal", sourceType: "sale", sourceId: reversalId, reversalOfId: id, createdByUserId: context.tenant.userId }), db.insert(auditEvent).values(auditValues(context, "sale.reversed", "retail_sale", id, reason)), db.insert(idempotencyRecord).values(idempotencyValues(context.tenant, `sale.reverse.${id}`, idempotency, reversalId, response))]); return response;
}

export async function createStockTransfer(env: Env, request: Request, body: Record<string, unknown>) {
	const context = await requireProductContext(env, request); requireManager(context.tenant); assertKeys(body, ["destinationBranchId", "itemId", "quantityMilli", "reason"]); const idempotency = await readIdempotency(env, request, context.tenant, "stock.transfer", body); if (idempotency.replay) return idempotency.replay;
	const destinationBranchId = textValue(body.destinationBranchId)!; if (destinationBranchId === context.branch.branchId || !(await canAccessBranch(env, context.tenant, destinationBranchId))) throw new RequestError(400, "INVALID_BRANCH"); const itemId = textValue(body.itemId)!; const quantityMilli = integerValue(body.quantityMilli, "INVALID_QUANTITY", 1); const reason = textValue(body.reason, "REASON_REQUIRED", 300)!; await enforceStock(env, context.tenant.organizationId, context.branch.branchId, [{ itemId, quantityMilli, unitAmountMinor: null }]);
	const db = getTenantDb(env, context.tenant.organizationId); const [item] = await db.select().from(inventoryItem).where(and(eq(inventoryItem.id, itemId), eq(inventoryItem.organizationId, context.tenant.organizationId))).limit(1); if (!item) throw new RequestError(400, "INVALID_ITEM"); const id = crypto.randomUUID(); const response = { id, itemId, quantityMilli, sourceBranchId: context.branch.branchId, destinationBranchId };
	await db.batch([db.insert(stockMovement).values({ id: crypto.randomUUID(), organizationId: context.tenant.organizationId, branchId: context.branch.branchId, itemId, kind: "transfer_out", quantityMilli: -quantityMilli, unitCostMinor: item.costMinor, description: "Stock transfer out", sourceType: "stock_transfer", sourceId: id, createdByUserId: context.tenant.userId }), db.insert(stockMovement).values({ id: crypto.randomUUID(), organizationId: context.tenant.organizationId, branchId: destinationBranchId, itemId, kind: "transfer_in", quantityMilli, unitCostMinor: item.costMinor, description: "Stock transfer in", sourceType: "stock_transfer", sourceId: id, createdByUserId: context.tenant.userId }), db.insert(auditEvent).values(auditValues(context, "stock.transferred", "stock_transfer", id, reason, { itemId, quantityMilli, destinationBranchId })), db.insert(idempotencyRecord).values(idempotencyValues(context.tenant, "stock.transfer", idempotency, id, response))]); return response;
}

export async function listStockTransfers(env: Env, request: Request) { const context = await requireProductContext(env, request); const rows = await getTenantDb(env, context.tenant.organizationId).select().from(stockMovement).where(and(eq(stockMovement.organizationId, context.tenant.organizationId), eq(stockMovement.sourceType, "stock_transfer"))).orderBy(desc(stockMovement.createdAt)); const visible = rows.filter((row) => row.branchId === context.branch.branchId); return { transfers: [...new Set(visible.map((row) => row.sourceId))].map((id) => ({ id, movements: rows.filter((row) => row.sourceId === id) })) }; }

export async function reverseStockTransfer(env: Env, request: Request, id: string, body: Record<string, unknown>) {
	const context = await requireProductContext(env, request); requireManager(context.tenant); assertKeys(body, ["reason"]); const reason = textValue(body.reason, "REASON_REQUIRED", 300)!; const idempotency = await readIdempotency(env, request, context.tenant, `stock.transfer.reverse.${id}`, body); if (idempotency.replay) return idempotency.replay; const db = getTenantDb(env, context.tenant.organizationId);
	const original = await db.select().from(stockMovement).where(and(eq(stockMovement.organizationId, context.tenant.organizationId), eq(stockMovement.sourceType, "stock_transfer"), eq(stockMovement.sourceId, id))).orderBy(asc(stockMovement.createdAt)); if (original.length !== 2 || !original.some((row) => row.branchId === context.branch.branchId)) throw new AuthError(404, "RESOURCE_NOT_FOUND"); const [already] = await db.select({ id: stockMovement.id }).from(stockMovement).where(and(eq(stockMovement.sourceType, "stock_transfer_reversal"), eq(stockMovement.reversalOfId, id))).limit(1); if (already) throw new RequestError(409, "ALREADY_REVERSED"); const destinationEffect = original.find((row) => row.quantityMilli > 0)!; await enforceStock(env, context.tenant.organizationId, destinationEffect.branchId, [{ itemId: destinationEffect.itemId, quantityMilli: destinationEffect.quantityMilli, unitAmountMinor: null }]); const reversalId = crypto.randomUUID(); const reverse = (row: typeof original[number]) => db.insert(stockMovement).values({ id: crypto.randomUUID(), organizationId: context.tenant.organizationId, branchId: row.branchId, itemId: row.itemId, kind: row.quantityMilli > 0 ? "transfer_reversal_out" : "transfer_reversal_in", quantityMilli: -row.quantityMilli, unitCostMinor: row.unitCostMinor, description: `Reversal: ${row.description}`, sourceType: "stock_transfer_reversal", sourceId: reversalId, reversalOfId: id, createdByUserId: context.tenant.userId }); const response = { id: reversalId, reversalOfId: id, status: "reversed" }; await db.batch([reverse(original[0]!), reverse(original[1]!), db.insert(auditEvent).values(auditValues(context, "stock.transfer_reversed", "stock_transfer", id, reason)), db.insert(idempotencyRecord).values(idempotencyValues(context.tenant, `stock.transfer.reverse.${id}`, idempotency, reversalId, response))]); return response;
}
