import { and, asc, desc, eq, gte, lte, sql, sum } from "drizzle-orm";
import { getTenantDb } from "../db";
import { financialMovement, inventoryItem, paymentMethod, retailSale, stockMovement, washAssignment, washTicket } from "../db/schema";
import { requireManager, requireProductContext } from "./domain";

function dateRange(request: Request) {
	const url = new URL(request.url); const today = new Date(); const fallbackFrom = new Date(today.getFullYear(), today.getMonth(), today.getDate());
	const fromValue = url.searchParams.get("from"); const toValue = url.searchParams.get("to"); const from = fromValue ? new Date(`${fromValue}T00:00:00`) : fallbackFrom; const to = toValue ? new Date(`${toValue}T23:59:59.999`) : new Date(fallbackFrom.getTime() + 86_399_999);
	return { from: Number.isNaN(from.getTime()) ? fallbackFrom : from, to: Number.isNaN(to.getTime()) ? today : to };
}

export async function getDashboard(env: Env, request: Request) {
	const context = await requireProductContext(env, request); const db = getTenantDb(env, context.tenant.organizationId); const { from, to } = dateRange(request); const ticketScope = and(eq(washTicket.organizationId, context.tenant.organizationId), eq(washTicket.branchId, context.branch.branchId), gte(washTicket.createdAt, from), lte(washTicket.createdAt, to)); const moneyScope = and(eq(financialMovement.organizationId, context.tenant.organizationId), eq(financialMovement.branchId, context.branch.branchId), gte(financialMovement.createdAt, from), lte(financialMovement.createdAt, to));
	const [tickets, movements, balances, stock] = await Promise.all([
		db.select({ status: washTicket.status, count: sql<number>`count(*)`, totalMinor: sum(washTicket.totalMinor) }).from(washTicket).where(ticketScope).groupBy(washTicket.status),
		db.select({ kind: financialMovement.kind, totalMinor: sum(financialMovement.amountMinor) }).from(financialMovement).where(moneyScope).groupBy(financialMovement.kind),
		db.select({ paymentMethodId: financialMovement.paymentMethodId, balanceMinor: sum(financialMovement.amountMinor) }).from(financialMovement).where(and(eq(financialMovement.organizationId, context.tenant.organizationId), eq(financialMovement.branchId, context.branch.branchId))).groupBy(financialMovement.paymentMethodId),
		db.select({ itemId: stockMovement.itemId, quantityMilli: sum(stockMovement.quantityMilli) }).from(stockMovement).where(and(eq(stockMovement.organizationId, context.tenant.organizationId), eq(stockMovement.branchId, context.branch.branchId))).groupBy(stockMovement.itemId),
	]);
	const methods = await db.select().from(paymentMethod).where(eq(paymentMethod.organizationId, context.tenant.organizationId)).orderBy(asc(paymentMethod.displayOrder)); const items = await db.select().from(inventoryItem).where(and(eq(inventoryItem.organizationId, context.tenant.organizationId), eq(inventoryItem.isActive, true)));
	const incomeMinor = movements.filter((row) => ["ticket_income", "retail_income"].includes(row.kind)).reduce((total, row) => total + Number(row.totalMinor ?? 0), 0); const expenseMinor = -movements.filter((row) => ["expense", "purchase"].includes(row.kind)).reduce((total, row) => total + Number(row.totalMinor ?? 0), 0);
	return { currency: context.currency, period: { from, to }, queue: { waiting: tickets.find((row) => row.status === "waiting")?.count ?? 0, inProgress: tickets.find((row) => row.status === "in_progress")?.count ?? 0, ready: tickets.find((row) => row.status === "ready")?.count ?? 0 }, washes: tickets.filter((row) => row.status !== "cancelled").reduce((total, row) => total + Number(row.count), 0), washRevenueMinor: tickets.filter((row) => row.status !== "cancelled").reduce((total, row) => total + Number(row.totalMinor ?? 0), 0), incomeMinor, expenseMinor, netCashFlowMinor: movements.reduce((total, row) => total + Number(row.totalMinor ?? 0), 0), balances: methods.map((method) => ({ id: method.id, name: method.name, systemKey: method.systemKey, balanceMinor: Number(balances.find((row) => row.paymentMethodId === method.id)?.balanceMinor ?? 0) })), lowStock: items.map((item) => ({ id: item.id, name: item.name, quantityMilli: Number(stock.find((row) => row.itemId === item.id)?.quantityMilli ?? 0), lowStockMilli: item.lowStockMilli })).filter((item) => item.quantityMilli <= item.lowStockMilli) };
}

export async function getWashReport(env: Env, request: Request) { const context = await requireProductContext(env, request); const { from, to } = dateRange(request); return { currency: context.currency, tickets: await getTenantDb(env, context.tenant.organizationId).select().from(washTicket).where(and(eq(washTicket.organizationId, context.tenant.organizationId), eq(washTicket.branchId, context.branch.branchId), gte(washTicket.createdAt, from), lte(washTicket.createdAt, to))).orderBy(desc(washTicket.createdAt)).limit(1000) }; }

export async function getFinanceReport(env: Env, request: Request) { const context = await requireProductContext(env, request); requireManager(context.tenant); const { from, to } = dateRange(request); const db = getTenantDb(env, context.tenant.organizationId); const movements = await db.select().from(financialMovement).where(and(eq(financialMovement.organizationId, context.tenant.organizationId), eq(financialMovement.branchId, context.branch.branchId), gte(financialMovement.createdAt, from), lte(financialMovement.createdAt, to))).orderBy(desc(financialMovement.createdAt)).limit(2000); return { currency: context.currency, movements, incomeMinor: movements.filter((row) => row.amountMinor > 0 && !row.kind.startsWith("transfer")).reduce((total, row) => total + row.amountMinor, 0), outflowMinor: -movements.filter((row) => row.amountMinor < 0 && !row.kind.startsWith("transfer")).reduce((total, row) => total + row.amountMinor, 0), netMinor: movements.reduce((total, row) => total + row.amountMinor, 0) }; }

export async function getInventoryReport(env: Env, request: Request) { const context = await requireProductContext(env, request); requireManager(context.tenant); const db = getTenantDb(env, context.tenant.organizationId); const items = await db.select().from(inventoryItem).where(eq(inventoryItem.organizationId, context.tenant.organizationId)).orderBy(asc(inventoryItem.name)); const quantities = await db.select({ itemId: stockMovement.itemId, quantityMilli: sum(stockMovement.quantityMilli) }).from(stockMovement).where(and(eq(stockMovement.organizationId, context.tenant.organizationId), eq(stockMovement.branchId, context.branch.branchId))).groupBy(stockMovement.itemId); return { currency: context.currency, items: items.map((item) => ({ ...item, quantityMilli: Number(quantities.find((row) => row.itemId === item.id)?.quantityMilli ?? 0), estimatedCostMinor: Math.round(Number(quantities.find((row) => row.itemId === item.id)?.quantityMilli ?? 0) * item.costMinor / 1000) })) }; }

export async function getSalesReport(env: Env, request: Request) { const context = await requireProductContext(env, request); requireManager(context.tenant); const { from, to } = dateRange(request); const sales = await getTenantDb(env, context.tenant.organizationId).select().from(retailSale).where(and(eq(retailSale.organizationId, context.tenant.organizationId), eq(retailSale.branchId, context.branch.branchId), gte(retailSale.createdAt, from), lte(retailSale.createdAt, to))).orderBy(desc(retailSale.createdAt)).limit(1000); return { currency: context.currency, sales, totalMinor: sales.reduce((total, sale) => total + sale.totalMinor, 0) }; }

export async function getCommissionReport(env: Env, request: Request) { const context = await requireProductContext(env, request); requireManager(context.tenant); const { from, to } = dateRange(request); const rows = await getTenantDb(env, context.tenant.organizationId).select({ assignment: washAssignment, ticketNumber: washTicket.number, deliveredAt: washTicket.deliveredAt }).from(washAssignment).innerJoin(washTicket, eq(washTicket.id, washAssignment.ticketId)).where(and(eq(washAssignment.organizationId, context.tenant.organizationId), eq(washTicket.branchId, context.branch.branchId), eq(washTicket.status, "delivered"), gte(washTicket.deliveredAt, from), lte(washTicket.deliveredAt, to))).orderBy(desc(washTicket.deliveredAt)); return { currency: context.currency, commissions: rows.map((row) => ({ ...row.assignment, ticketNumber: row.ticketNumber, deliveredAt: row.deliveredAt })), totalMinor: rows.reduce((total, row) => total + row.assignment.commissionMinor, 0) }; }

function csvCell(value: unknown) { const text = String(value ?? ""); const safe = /^[=+\-@]/.test(text) ? `'${text}` : text; return `"${safe.replace(/"/g, '""')}"`; }
export async function exportReport(env: Env, request: Request, report: string) {
	let rows: Record<string, unknown>[]; if (report === "washes") rows = (await getWashReport(env, request)).tickets; else if (report === "finance") rows = (await getFinanceReport(env, request)).movements; else if (report === "inventory") rows = (await getInventoryReport(env, request)).items; else if (report === "retail-sales") rows = (await getSalesReport(env, request)).sales; else if (report === "commissions") rows = (await getCommissionReport(env, request)).commissions; else throw new Error("REPORT_NOT_FOUND");
	const keys = Array.from(new Set(rows.flatMap((row) => Object.keys(row)))); return [keys.map(csvCell).join(","), ...rows.map((row) => keys.map((key) => csvCell(row[key])).join(","))].join("\n");
}
